# Generated by Django 5.0.2 on 2024-03-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='edad',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
